"""
Known tracker / analytics / ads SDK package signatures, used to flag
third-party libraries bundled inside an analyzed APK.
"""

KNOWN_TRACKERS: dict[str, str] = {
    "google.android.gms.measurement": "Google Analytics / Firebase",
    "facebook.appevents": "Facebook Analytics",
    "appsflyer": "AppsFlyer",
    "mixpanel": "Mixpanel",
    "flurry": "Flurry",
    "adjust": "Adjust",
    "amplitude": "Amplitude",
    "kochava": "Kochava",
    "branch.io": "Branch",
    "segment.analytics": "Segment",
    "yandex.metrica": "Yandex Metrica",
    "clevertap": "CleverTap",
    "moengage": "MoEngage",
    "localytics": "Localytics",
    "tenjin": "Tenjin",
    "snowplow": "Snowplow Analytics",
    "crashlytics": "Crashlytics (Google)",
    "bugsnag": "Bugsnag",
    "sentry": "Sentry",
    "newrelic": "New Relic",
    "datadog": "Datadog",
    "instabug": "Instabug",
    "appdynamics": "AppDynamics",
    "google.android.gms.ads": "Google AdMob",
    "facebook.ads": "Facebook Audience Network",
    "unity3d.ads": "Unity Ads",
    "applovin": "AppLovin",
    "vungle": "Vungle",
    "ironsource": "ironSource",
    "chartboost": "Chartboost",
    "inmobi": "InMobi",
    "bytedance": "TikTok / Pangle Ads",
    "amazon.device.ads": "Amazon Ads",
    "mopub": "MoPub (Twitter)",
    "tapjoy": "Tapjoy",
    "adcolony": "AdColony",
    "onesignal": "OneSignal",
    "urbanairship": "Airship",
    "braze": "Braze",
    "pushwoosh": "Pushwoosh",
    "batch": "Batch",
    "leanplum": "Leanplum",
}
