name: '[Windows] Build APKViewer'

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Set up Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 'Install Python dependencies'
        run: |
          & "$env:pythonLocation\python.exe" -m pip install --upgrade pip
          & "$env:pythonLocation\python.exe" -m pip install -r requirements.txt
          & "$env:pythonLocation\python.exe" -m pip install nuitka zstandard

      - name: 'Build executable with Nuitka'
        run: |
          & "$env:pythonLocation\python.exe" -m nuitka `
              --standalone `
              --onefile `
              --assume-yes-for-downloads `
              --output-dir=dist `
              --output-filename=APKViewer.exe `
              --windows-console-mode=disable `
              --include-package-data=androguard `
              --include-data-dir=assets=assets `
              --enable-plugin=tk-inter `
              --nofollow-import-to=frida `
              --lto=yes `
              main.py

      - name: 'Upload binary to release'
        uses: softprops/action-gh-release@v2
        with:
          files: dist/APKViewer.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
